/**
 * Traducción al español de los nombres de lugar que llegan de GDELT/ACLED.
 *
 * GDELT entrega los topónimos en inglés ("Tehran, Tehran, Iran"); aquí se
 * traducen el país (última parte del nombre) y las ciudades/regiones con
 * exónimo español conocido. Lo que no está en los diccionarios se deja tal
 * cual: casi siempre es un nombre local sin forma española propia.
 */

// País en inglés (como lo escribe GDELT/ACLED) -> español.
// Incluye las variantes con coma ("Korea, Republic Of") del campo FullName.
const PAISES = {
  "Afghanistan": "Afganistán",
  "Albania": "Albania",
  "Algeria": "Argelia",
  "Andorra": "Andorra",
  "Angola": "Angola",
  "Antigua And Barbuda": "Antigua y Barbuda",
  "Argentina": "Argentina",
  "Armenia": "Armenia",
  "Australia": "Australia",
  "Austria": "Austria",
  "Azerbaijan": "Azerbaiyán",
  "Bahamas, The": "Bahamas",
  "Bahamas": "Bahamas",
  "Bahrain": "Baréin",
  "Bangladesh": "Bangladés",
  "Barbados": "Barbados",
  "Belarus": "Bielorrusia",
  "Belgium": "Bélgica",
  "Belize": "Belice",
  "Benin": "Benín",
  "Bermuda": "Bermudas",
  "Bhutan": "Bután",
  "Bolivia": "Bolivia",
  "Bosnia-Herzegovina": "Bosnia y Herzegovina",
  "Bosnia And Herzegovina": "Bosnia y Herzegovina",
  "Botswana": "Botsuana",
  "Brazil": "Brasil",
  "Brunei": "Brunéi",
  "Bulgaria": "Bulgaria",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cambodia": "Camboya",
  "Cameroon": "Camerún",
  "Canada": "Canadá",
  "Cape Verde": "Cabo Verde",
  "Central African Republic": "República Centroafricana",
  "Chad": "Chad",
  "Chile": "Chile",
  "China": "China",
  "Colombia": "Colombia",
  "Comoros": "Comoras",
  "Congo, Democratic Republic Of The": "República Democrática del Congo",
  "Democratic Republic Of The Congo": "República Democrática del Congo",
  "Congo, Republic Of The": "República del Congo",
  "Congo": "Congo",
  "Cook Islands": "Islas Cook",
  "Costa Rica": "Costa Rica",
  "Cote D'ivoire": "Costa de Marfil",
  "Croatia": "Croacia",
  "Cuba": "Cuba",
  "Cyprus": "Chipre",
  "Czech Republic": "República Checa",
  "Czechia": "Chequia",
  "Denmark": "Dinamarca",
  "Djibouti": "Yibuti",
  "Dominica": "Dominica",
  "Dominican Republic": "República Dominicana",
  "East Timor": "Timor Oriental",
  "Timor-Leste": "Timor Oriental",
  "Ecuador": "Ecuador",
  "Egypt": "Egipto",
  "El Salvador": "El Salvador",
  "Equatorial Guinea": "Guinea Ecuatorial",
  "Eritrea": "Eritrea",
  "Estonia": "Estonia",
  "Eswatini": "Esuatini",
  "Swaziland": "Esuatini",
  "Ethiopia": "Etiopía",
  "Fiji": "Fiyi",
  "Finland": "Finlandia",
  "France": "Francia",
  "Gabon": "Gabón",
  "Gambia, The": "Gambia",
  "Gambia": "Gambia",
  "Gaza Strip": "Franja de Gaza",
  "Georgia": "Georgia",
  "Germany": "Alemania",
  "Ghana": "Ghana",
  "Greece": "Grecia",
  "Greenland": "Groenlandia",
  "Grenada": "Granada",
  "Guadeloupe": "Guadalupe",
  "Guatemala": "Guatemala",
  "Guinea-Bissau": "Guinea-Bisáu",
  "Guinea": "Guinea",
  "Guyana": "Guyana",
  "Haiti": "Haití",
  "Honduras": "Honduras",
  "Hong Kong": "Hong Kong",
  "Hungary": "Hungría",
  "Iceland": "Islandia",
  "India": "India",
  "Indonesia": "Indonesia",
  "Iran": "Irán",
  "Iraq": "Irak",
  "Ireland": "Irlanda",
  "Israel": "Israel",
  "Italy": "Italia",
  "Jamaica": "Jamaica",
  "Japan": "Japón",
  "Jarvis Island": "Isla Jarvis",
  "Jersey": "Jersey",
  "Jordan": "Jordania",
  "Kazakhstan": "Kazajistán",
  "Kenya": "Kenia",
  "Kiribati": "Kiribati",
  "Korea, Democratic People's Republic Of": "Corea del Norte",
  "North Korea": "Corea del Norte",
  "Korea, Republic Of": "Corea del Sur",
  "South Korea": "Corea del Sur",
  "Kosovo": "Kosovo",
  "Kuwait": "Kuwait",
  "Kyrgyzstan": "Kirguistán",
  "Laos": "Laos",
  "Latvia": "Letonia",
  "Lebanon": "Líbano",
  "Lesotho": "Lesoto",
  "Liberia": "Liberia",
  "Libya": "Libia",
  "Liechtenstein": "Liechtenstein",
  "Lithuania": "Lituania",
  "Luxembourg": "Luxemburgo",
  "Macau": "Macao",
  "Macedonia": "Macedonia del Norte",
  "North Macedonia": "Macedonia del Norte",
  "Madagascar": "Madagascar",
  "Malawi": "Malaui",
  "Malaysia": "Malasia",
  "Maldives": "Maldivas",
  "Mali": "Malí",
  "Malta": "Malta",
  "Marshall Islands": "Islas Marshall",
  "Mauritania": "Mauritania",
  "Mauritius": "Mauricio",
  "Mexico": "México",
  "Micronesia, Federated States Of": "Micronesia",
  "Moldova": "Moldavia",
  "Monaco": "Mónaco",
  "Mongolia": "Mongolia",
  "Montenegro": "Montenegro",
  "Morocco": "Marruecos",
  "Mozambique": "Mozambique",
  "Myanmar": "Myanmar (Birmania)",
  "Burma": "Myanmar (Birmania)",
  "Namibia": "Namibia",
  "Nauru": "Nauru",
  "Nepal": "Nepal",
  "Netherlands, The": "Países Bajos",
  "Netherlands": "Países Bajos",
  "New Zealand": "Nueva Zelanda",
  "Nicaragua": "Nicaragua",
  "Nigeria": "Nigeria",
  "Niger": "Níger",
  "Norway": "Noruega",
  "Oceans": "Océanos",
  "Oman": "Omán",
  "Pakistan": "Pakistán",
  "Palau": "Palaos",
  "Panama": "Panamá",
  "Papua New Guinea": "Papúa Nueva Guinea",
  "Paraguay": "Paraguay",
  "Peru": "Perú",
  "Philippines": "Filipinas",
  "Poland": "Polonia",
  "Portugal": "Portugal",
  "Puerto Rico": "Puerto Rico",
  "Qatar": "Catar",
  "Reunion": "Reunión",
  "Romania": "Rumanía",
  "Russia": "Rusia",
  "Rwanda": "Ruanda",
  "Saint Kitts And Nevis": "San Cristóbal y Nieves",
  "Saint Lucia": "Santa Lucía",
  "Saint Vincent And The Grenadines": "San Vicente y las Granadinas",
  "Samoa": "Samoa",
  "San Marino": "San Marino",
  "Sao Tome And Principe": "Santo Tomé y Príncipe",
  "Saudi Arabia": "Arabia Saudí",
  "Senegal": "Senegal",
  "Serbia (general)": "Serbia",
  "Serbia": "Serbia",
  "Seychelles": "Seychelles",
  "Sierra Leone": "Sierra Leona",
  "Singapore": "Singapur",
  "Slovak Republic": "Eslovaquia",
  "Slovakia": "Eslovaquia",
  "Slovenia": "Eslovenia",
  "Solomon Islands": "Islas Salomón",
  "Somalia": "Somalia",
  "South Africa": "Sudáfrica",
  "South Sudan": "Sudán del Sur",
  "Spain": "España",
  "Sri Lanka": "Sri Lanka",
  "Sudan": "Sudán",
  "Suriname": "Surinam",
  "Sweden": "Suecia",
  "Switzerland": "Suiza",
  "Syria": "Siria",
  "Taiwan": "Taiwán",
  "Tajikistan": "Tayikistán",
  "Tanzania": "Tanzania",
  "Thailand": "Tailandia",
  "Togo": "Togo",
  "Tonga": "Tonga",
  "Trinidad And Tobago": "Trinidad y Tobago",
  "Tunisia": "Túnez",
  "Turkey": "Turquía",
  "Turkmenistan": "Turkmenistán",
  "Tuvalu": "Tuvalu",
  "Uganda": "Uganda",
  "Ukraine": "Ucrania",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  "United Kingdom": "Reino Unido",
  "United States": "Estados Unidos",
  "Uruguay": "Uruguay",
  "Uzbekistan": "Uzbekistán",
  "Vanuatu": "Vanuatu",
  "Vatican City": "Ciudad del Vaticano",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnam",
  "West Bank": "Cisjordania",
  "Western Sahara": "Sáhara Occidental",
  "Yemen": "Yemen",
  "Zambia": "Zambia",
  "Zimbabwe": "Zimbabue",
};

// Ciudades y regiones con exónimo español asentado (se aplican por segmento).
const EXONIMOS = {
  "Addis Ababa": "Adís Abeba",
  "Alexandria": "Alejandría",
  "Algiers": "Argel",
  "Amman": "Ammán",
  "Amsterdam": "Ámsterdam",
  "Antwerp": "Amberes",
  "Asuncion": "Asunción",
  "Athens": "Atenas",
  "Baghdad": "Bagdad",
  "Basel": "Basilea",
  "Beijing": "Pekín",
  "Belgrade": "Belgrado",
  "Bern": "Berna",
  "Berlin": "Berlín",
  "Bogota": "Bogotá",
  "Bordeaux": "Burdeos",
  "Brasilia": "Brasilia",
  "Brussels": "Bruselas",
  "Bucharest": "Bucarest",
  "Cairo": "El Cairo",
  "Cape Town": "Ciudad del Cabo",
  "Cologne": "Colonia",
  "Copenhagen": "Copenhague",
  "Cracow": "Cracovia",
  "Damascus": "Damasco",
  "Dresden": "Dresde",
  "Dublin": "Dublín",
  "Edinburgh": "Edimburgo",
  "Florence": "Florencia",
  "Frankfurt": "Fráncfort",
  "Geneva": "Ginebra",
  "Genoa": "Génova",
  "Gothenburg": "Gotemburgo",
  "Guatemala City": "Ciudad de Guatemala",
  "Havana": "La Habana",
  "Isfahan": "Isfahán",
  "Istanbul": "Estambul",
  "Jerusalem": "Jerusalén",
  "Johannesburg": "Johannesburgo",
  "Khartoum": "Jartum",
  "Krakow": "Cracovia",
  "Kyiv": "Kiev",
  "Lisbon": "Lisboa",
  "London": "Londres",
  "Marseille": "Marsella",
  "Mecca": "La Meca",
  "Mexico City": "Ciudad de México",
  "Milan": "Milán",
  "Moscow": "Moscú",
  "Munich": "Múnich",
  "Naples": "Nápoles",
  "New Delhi": "Nueva Delhi",
  "New Orleans": "Nueva Orleans",
  "New York": "Nueva York",
  "Ouagadougou": "Uagadugú",
  "Panama City": "Ciudad de Panamá",
  "Paris": "París",
  "Philadelphia": "Filadelfia",
  "Porto": "Oporto",
  "Port-Au-Prince": "Puerto Príncipe",
  "Prague": "Praga",
  "Rio De Janeiro": "Río de Janeiro",
  "Riyadh": "Riad",
  "Rome": "Roma",
  "Rangoon": "Rangún",
  "Saint Petersburg": "San Petersburgo",
  "Sao Paulo": "São Paulo",
  "Seoul": "Seúl",
  "Shanghai": "Shanghái",
  "Sofia": "Sofía",
  "Stockholm": "Estocolmo",
  "Strasbourg": "Estrasburgo",
  "Sydney": "Sídney",
  "Taipei": "Taipéi",
  "Tashkent": "Taskent",
  "Tehran": "Teherán",
  "The Hague": "La Haya",
  "Tokyo": "Tokio",
  "Tripoli": "Trípoli",
  "Tunis": "Túnez",
  "Turin": "Turín",
  "Venice": "Venecia",
  "Vienna": "Viena",
  "Warsaw": "Varsovia",
  "Zurich": "Zúrich",
};

// Claves de país de la más larga a la más corta, para que
// "Korea, Republic Of" gane a "Republic Of" y similares.
const CLAVES_PAIS = Object.keys(PAISES).sort((a, b) => b.length - a.length);

/** Traduce solo un nombre de país ("United Kingdom" -> "Reino Unido"). */
export function traducirPais(nombre) {
  const limpio = String(nombre || "").trim();
  return PAISES[limpio] || limpio;
}

/**
 * Traduce un nombre de lugar completo de GDELT/ACLED
 * ("Tehran, Tehran, Iran" -> "Teherán, Teherán, Irán").
 */
export function traducirLugar(nombre) {
  let resto = String(nombre || "").trim().replace(/[\s,]+$/, "");
  if (!resto) return nombre;

  // 1) El país es el final de la cadena (puede contener comas)
  let pais = "";
  for (const clave of CLAVES_PAIS) {
    if (resto === clave) {
      return PAISES[clave];
    }
    if (resto.endsWith(", " + clave)) {
      pais = PAISES[clave];
      resto = resto.slice(0, -(clave.length + 2));
      break;
    }
  }

  // 2) Ciudad y región: exónimo si existe, tal cual si no.
  // GDELT usa "País (general)" como región comodín: se traduce el país.
  const partes = resto.split(", ").map((p) => {
    if (EXONIMOS[p]) return EXONIMOS[p];
    const general = /^(.+) \(general\)$/.exec(p);
    if (general) return (PAISES[general[1]] || EXONIMOS[general[1]] || general[1]) + " (general)";
    return p;
  });
  if (pais) partes.push(pais);
  return partes.join(", ");
}
